# Generated by Django 5.1.1 on 2024-09-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_todo_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='done',
        ),
        migrations.AddField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(choices=[(True, 'Выполнено'), (False, 'Не выполнено')], default=False),
        ),
    ]
